In [63]:
import numpy as np

# Inicilizar arrays


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr1 = np.zeros(10)

In [ ]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
mat = np.zeros((3,3), dtype="int8")

In [ ]:
mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
mat.nbytes

9

In [ ]:
mat = np.ones((3,3))

In [ ]:
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
mat.dtype

dtype('float64')

In [ ]:
mat.itemsize

8

In [ ]:
mat = np.full((5,5), 99)

In [ ]:
mat.dtype

NameError: name 'mat' is not defined

In [ ]:
mat = np.full((5,5), 99, dtype='int8')

In [ ]:
mat

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]], dtype=int8)

In [ ]:
mat2 = np.full_like(mat, 14 )

In [ ]:
print(mat)
print("---------------")
print(mat2)


[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]
---------------
[[14 14 14 14 14]
 [14 14 14 14 14]
 [14 14 14 14 14]
 [14 14 14 14 14]
 [14 14 14 14 14]]


In [ ]:
np.random.rand(4,2)

array([[0.51397704, 0.31748177],
       [0.85449115, 0.33311095],
       [0.44035454, 0.8284571 ],
       [0.40088054, 0.9236083 ]])

In [ ]:
np.random.random((2,2))

array([[0.35594804, 0.08908099],
       [0.06099766, 0.41623897]])

In [ ]:
aux = np.random.randn(4,2)
aux

array([[-0.00261994,  1.72018073],
       [-0.17240999, -1.66440424],
       [-0.05964127,  0.76430213],
       [-1.96719994,  0.36678317]])

In [ ]:
np.average(aux)

-0.1268761705318418

In [ ]:
np.std(aux)

1.1303945733332807

In [ ]:
np.random.randint(192,3213, size=(3,3))

array([[2745, 1382, 3176],
       [1997, 2626, 1898],
       [ 733,  554,  467]])

In [ ]:
np.random.random_sample(aux.shape) # ..._like

In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
aux = np.array([[2745, 1382, 3176], ])
aux

array([[2745, 1382, 3176]])

In [78]:
np.repeat(aux, 3, axis=0)

array([[2745, 1382, 3176],
       [2745, 1382, 3176],
       [2745, 1382, 3176]])

In [83]:
newMat = np.random.randint(1,10, size=(5,2))
newMat

array([[1, 9],
       [8, 8],
       [5, 1],
       [6, 1],
       [8, 4]])

In [80]:
np.sum(newMat)

122

In [84]:
np.sum(newMat, axis=0) #col

array([28, 23])

In [85]:
np.sum(newMat, axis=1) # linhas

array([10, 16,  6,  7, 12])

In [86]:
newMat.shape

(5, 2)

In [87]:
newMat.reshape(2,5)

array([[1, 9, 8, 8, 5],
       [1, 6, 1, 8, 4]])

In [88]:
newMat.reshape(1,10)

array([[1, 9, 8, 8, 5, 1, 6, 1, 8, 4]])

In [89]:
newMat.reshape(10,1)

array([[1],
       [9],
       [8],
       [8],
       [5],
       [1],
       [6],
       [1],
       [8],
       [4]])

# read file

In [90]:
fileData = np.loadtxt('data.txt', delimiter=',')

In [91]:
fileData

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [93]:
fileData.dtype

dtype('float64')

In [99]:
fileDataInt = fileData.astype('int32')
fileDataInt

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [98]:
fileDataInt.dtype

dtype('int32')

In [100]:
res = fileDataInt > 50
res

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [103]:
aux = fileData[res]

In [106]:
aux

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [105]:
aux[[4,1,2,5]]

array([ 55.,  75., 766., 999.])

In [108]:
np.any(fileData > 50)

True

In [107]:
np.any(fileData > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [109]:
np.any(fileData > 50, axis=1)

array([ True,  True,  True])

In [111]:
np.any(fileData, axis=1)

array([ True,  True,  True])

In [121]:
aux2 = np.array([3,55,81 ])
aux2

array([ 3, 55, 81])

In [124]:
res2 = (fileDataInt > 50) & (fileDataInt < 100)
res2

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [125]:
fileDataInt[res2]

array([75, 75, 55, 78, 76, 88], dtype=int32)