In [ ]:
import numpy as np


In [201]:
a_arr = [1, 2, 3]
b_arr = [4, 5, 6]

In [ ]:
a_arr

[1, 2, 3]

In [ ]:
a = np.array(a_arr)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
a.itemsize

8

In [ ]:
a.__len__()

3

In [ ]:
a.nbytes

24

In [ ]:
a.ndim

1

In [ ]:
s = a.shape
s

(3,)

In [ ]:
s[1]

IndexError: tuple index out of range

In [ ]:
s[0]

3

In [ ]:
a_arr = [ 9, 56, 11, 12, 13, 14, 15, 16]

In [ ]:
a = np.array(a_arr)
b = np.array(b_arr)

In [ ]:
a[1] = 99

In [ ]:
a

array([ 9, 99, 11, 12, 13, 14, 15, 16])

In [ ]:
mtx = np.array(
                    [
                      [1, 2, 3, 4, 5, 6, 7, 8],
                      [9,10,11,12,13,14,15,16],
                      [9,10,11,12,13,14,15,16]
                    ]
              )

In [ ]:
print(mtx)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
mtx.ndim

2

In [ ]:
mtx.itemsize

8

In [ ]:
mtx.nbytes

192

In [ ]:
lst = [1.2, 13. ,22.01]
lst

[1.2, 13.0, 22.01]

In [ ]:
a_f = np.array(lst)

In [ ]:
a_f.nbytes

24

In [ ]:
a_f.itemsize

8

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.itemsize

8

In [ ]:
b.nbytes

24

In [100]:
b.dtype

dtype('int64')

In [105]:
c = np.array([4, 5, 6], dtype='uint8')
c

array([4, 5, 6], dtype=uint8)

In [110]:
c.dtype

dtype('uint8')

In [109]:
c.itemsize

1

In [108]:
c.nbytes

3

In [107]:
print("b:", b)
print("c:", c)

b: [4 5 6]
c: [4 5 6]


In [106]:
print("b nbytes:", b.nbytes)
print("c nbytes:", c.nbytes)

b nbytes: 24
c nbytes: 3


In [112]:
a_arr

[9, 56, 11, 12, 13, 14, 15, 16]

In [113]:
np.max(a_arr)

56

In [114]:
v1 = np.array(a_arr)
v1.nbytes

64

In [115]:
v2 = np.array(a_arr, dtype="int8")
v2.nbytes

8

In [154]:
mtx = np.array(
                    [
                      [1, 2, 3, 4, 5, 6, 7 , 8],
                      [9,10,11,12,13,14,15 ,16],
                      [9,10,11,12,13,14,45,16]
                    ],
                    dtype="int8"
              )

In [137]:
mtx.dtype

dtype('int8')

In [138]:
mtx.nbytes

24

In [139]:
mtx.max()

45

In [140]:
mtx.min()

1

In [142]:
mtx.mean()

11.083333333333334

In [156]:
mtx.itemset(0, 99)

In [159]:
mtx

array([[ 99,   2,   3, 100,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16],
       [  9,  10,  11,  12,  13,  14,  45,  16]], dtype=int8)

In [162]:
mtx.itemset(8, 120)


In [163]:
mtx.itemset(3, 100)


In [164]:
mtx

array([[ 99,   2,   3, 100,   5,   6,   7,   8],
       [120,  10,  11,  12,  13,  14,  15,  16],
       [  9,  10,  11,  12,  13,  14,  45,  16]], dtype=int8)

In [165]:
mtx.shape

(3, 8)

In [168]:
mtx = np.array(     [
                      [
                        [1, 2, 3, 4, 5, 6, 7 , 8],
                        [9,10,11,12,13,14,15 ,16],
                        [9,10,11,12,13,14,45,16]
                      ],
                      [
                        [1, 2, 3, 4, 5, 6, 7 , 8],
                        [9,10,11,12,13,14,15 ,16],
                        [9,10,11,12,13,14,45,16]
                      ]
                    ],
                    dtype="int8"
              )

In [169]:
mtx.shape

(2, 3, 8)

In [170]:
mtx = np.array(
                    [
                      [1, 2, 3, 4, 5, 6, 7 , 8],
                      [9,10,11,12,13,14,15 ,16],
                      [9,10,11,12,13,14,45,16]
                    ],
                    dtype="int8"
              )

In [173]:
mtx[0, 0]

1

In [174]:
mtx[2, 4]

13

In [176]:
mtx[1, :]

array([ 9, 10, 11, 12, 13, 14, 15, 16], dtype=int8)

In [177]:
mtx[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 45, 16]], dtype=int8)

In [178]:
mtx[1 : ]

array([[ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 45, 16]], dtype=int8)

In [179]:
mtx

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 45, 16]], dtype=int8)

In [180]:
mtx[:, 2]

array([ 3, 11, 11], dtype=int8)

In [181]:
mtx[0, 1:6] # elm da llinha 0 da pos 1 a 5

array([2, 3, 4, 5, 6], dtype=int8)

In [182]:
mtx[0, 1:6 : 2]

array([2, 4, 6], dtype=int8)

In [183]:
mtx[:, 4]

array([ 5, 13, 13], dtype=int8)

In [184]:
mtx[:, 4] = [0, 0, 0]

In [185]:
mtx

array([[ 1,  2,  3,  4,  0,  6,  7,  8],
       [ 9, 10, 11, 12,  0, 14, 15, 16],
       [ 9, 10, 11, 12,  0, 14, 45, 16]], dtype=int8)

In [186]:
mtx[:, 4] = [0, 0, 0, 5] # a list a atribuir tem de ter as mesmas dim que o destino


ValueError: could not broadcast input array from shape (4,) into shape (3,)

In [187]:
mtx[0, 1:6 : 2]

array([2, 4, 6], dtype=int8)

In [189]:
mtx[0, 1:6 : 2] = [33, 33, 33]

In [190]:
mtx

array([[ 1, 33,  3, 33,  0, 33,  7,  8],
       [ 9, 10, 11, 12,  0, 14, 15, 16],
       [ 9, 10, 11, 12,  0, 14, 45, 16]], dtype=int8)

In [191]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [192]:
b * 2

array([ 8, 10, 12])

In [193]:
b - 10

array([-6, -5, -4])

In [194]:
b

array([4, 5, 6])

In [204]:
a_arr = [1,2,3]
a = np.array(a_arr)
a

array([1, 2, 3])

In [205]:
a + b

array([5, 7, 9])

In [207]:

print(a)
print(b)
a * b

[1 2 3]
[4 5 6]


array([ 4, 10, 18])

In [211]:
arr = np.array([[17, 18, 19, 20, 21, 22, 23, 24],
                [25, 26, 27, 28, 29, 30, 31, 32],
                [33, 34, 35, 36, 37, 38, 39, 40],
                [41, 42, 43, 44, 45, 46, 47, 48],
                [49, 50, 51, 52, 53, 54, 55, 56],
                [57, 58, 59, 60, 61, 62, 63, 64]])

In [212]:
arr

array([[17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [ ]:
# obter [34, 35, 36, 37, 38, 39, 40] # linha 3 da col  1 ate ao dim

In [ ]:
# obter [18, 26, 34, 42, 50, 58] #col 2

In [ ]:
#obter 26, 27, 29, 31 # linha 2, pos 1, 2, 4 6

In [ ]:
"""obter:

26, 27, 28, 29, 30, 31
34, 35, 36, 37, 38, 39
42, 43, 44, 45, 46, 47
50, 51, 52, 53, 54, 55

mat central
"""